### ISSUE TITLE
User Testing: 04-09-2017

### ISSUE THREAD

**Issue by ameliejyc** [ameliejyc/prereq-check#1]
- Users name:
- Users top three pain points using application:
  1.
  2.
  3.
- Users profile:
- Additional observations:

**Comment by astroash** [comment]
Users name: John Whiles
Users top three pain points using application:
1. (Find Kyu) Uncertainty on URL screen, tried to enter codewars url straight away, unsure of kyu level on summary vs codewars page
2. (Info about GH page) Unsure if others would recognise GH logo, doesn't understand graph, 'Edit website url' not obvious to change for a new user.
3.
Users profile: Current selection committee
Additional observations: 
- Some of the text wasn't clear eg change url
- input page was unclear, thought you would be able to type in individual names
- very grey
- found it easy to find info
- not sure of the relevance of meetup info
- would be nice to see applicants answers
- app's he likes citymapper (but cascading menus can be confusing), camera, whatsapp, signal, mobile banking, budgetting app, best apps have limited information
- not used similar apps but used the selection committees spreadsheet with similar info

**Comment by BartBucknill** [comment]
Users name: Bradley
Users top three pain points using application:

1. HTML Error check: what is it?
2. Why is scrape url a url not a username?
3. Not clear what the number on the fCC page refers to

Users profile: Lion Tamer and user researcher
Additional observations:
* Icons: concerned that people will not recognise icons in navbar
* Codewars social info: info such as number of comments could also be displayed
* Would be good to have links github pages page, and profiles for github, codewars, fCC, meetup
* github pages page could be a thumbnail
* apps used are github and old feed bulletins for things like psychology. doesn't use social media apps
* likes the colour scheme

**Comment by dangerdak** [comment]
Users name: Dan Sofer
Users top three pain points using application:
1. Some confusion about what info appears after scrape
2. Not immediately obvious what meetup icon is for
3. Thought summaries on summary page should be links, not obvious when on this page what the navbar is for

Users profile: selection committee

## Suggestions:
* Show commit messages
* Have the information for each summary point appear (dropdown?) when  you click them
* Danger of repo inferiority complex
* Ability to jump straight to summary page based on link (in spreadsheet)
  This would be part of the spreadsheet: a macro that would generate the link

## Additional observations:
* Trying to use fewer apps
* Doesn't like gitter
* Like banking apps
* Would use on mobile when chatting with selection group, but would use on desktop to reference with spreadsheet
* Anticipate and consider how this could be built into a larger application
* Last thing we do should be a PR to the FAC website to add link to this
* Application dates: maybe mid September, close in November

**Comment by BartBucknill** [comment]
Users name: Yahia
Users top three pain points using application:
1. Couldn't find personal page / github pages page report; when showed it felt that it mixed github info (number of repos) with personal page specific info.
2. Confused by 'scrape' button.
3. Thought that summary page 5 Kyu was the actual users level.

Users profile: Successful applicant currently on FAC.
Additional observations:
* Not used anything very similar, but was reminded of job application sites.
* Really wants animated growing lightbulb/plant.

**Comment by BartBucknill** [comment]
Users name:
Users top three pain points using application:
1. Some concern over what selection will look at, specifically questioned:
     * Questioned importance of repo and commit history info 
     * Questioned satisfaction rating on codewars - do sc look at this?
2. Wasn't clear what edit url was for (although found it quickly)
3. Struggled to find qithub site info briefly
Users profile: Successful applicant for FAC 12
Additional observations:
“Really cool”
Maybe don’t have everything on the first page but have it at the end instead so it’s less daunting.

**Comment by ameliejyc** [comment]
Users name: Abraham

### Users top three pain points using application:

1. Confusion over not being able to click on lightbulb

Occupation: graphic designer

### Suggestions:
- Would be good to be able to click on the summary lines which show incomplete prereqs to go straight to those websites to 'keep working on them'

### Additional observations:
- questioned if there is a minimum level of attendance for meetups
- questioned if the end of the prereq page means the end of the application. Or perhaps there should be a link to the application?
- assumes app will be more colourful
- started working on prereqs 3-4 weeks ago
- very interested to get more information on the application process!!
