### ISSUE TITLE
Show extra info about Codewars page

### ISSUE THREAD

**Issue by BartBucknill** [ameliejyc/prereq-check#15]
As a selection panel member I can see extra information about an applicant's Codewars profile.
As an applicant I can see extra information about my Codewars profile.

Acceptance criteria:

- [x] Page design should generally follow design mock up [here](https://projects.invisionapp.com/share/D8DB0IQX9#/screens/251474252)
- [x] Clearly displays prereq status for Kyu level and authoring of Kata at top.
- [x] Displays actual Kyu level
- [x] Displays honour points
~~- [ ] Displays date signed up~~
~~- [ ] Displays date last seen~~
- [x] Displays a link to any authored Kata, and for each Kata authored displays the following: 
~~- [ ] Satisfaction rating~~
- [x] Number of completions
- [x] Whether it is / is not out of Beta

![codewars page](https://user-images.githubusercontent.com/14337958/30063305-1f0c9834-9246-11e7-8ff2-fdc99d5f6cac.png)

**Comment by ameliejyc** [comment]
Update on information we can't retrieve from Codewars api:

Date signed up
Date last seen
Satisfaction rating of kata

We can however see the date the kata was written but we're unsure if this is valuable information.
