### ISSUE TITLE
Technical Spike - SCSS

### ISSUE THREAD

**Issue by astroash** [ameliejyc/prereq-check#19]
Research how to compile SCSS to CSS in when starting up the server/ pushing to heroku

**Comment by shiryz** [comment]
Hey @astroash, here are some useful ones:
https://github.com/msmichellegar/learn-sass-basics
http://sass-lang.com/guide
hope this helps :wink:

**Comment by ameliejyc** [comment]
Thanks for this @shiryz ! Very helpful 👍
