### ISSUE TITLE
Display freecodecamp prereq info: if they have completed the 4 subsections

### ISSUE THREAD

**Issue by astroash** [ameliejyc/prereq-check#4]
As a selection panel member I can see whether the applicant has completed the 4 subsections.
As an applicant I can see whether I have  completed the 4 subsections.

Acceptance criteria:

- [x] Display whether applicant has completed the 4 subsections
- [x] Display page should look like designed summary page (image to follow)

![summary page](https://user-images.githubusercontent.com/14337958/30059216-15bd506c-9236-11e7-9137-417d0f084705.png)

**Comment by BartBucknill** [comment]
freeCodeCamp does not have a working API. There is an API in development [here](https://fccapi.herokuapp.com/). Quincy responded to [my question about this on freeCodeCamp forums](https://forum.freecodecamp.org/t/does-freecodecamp-have-a-current-api/146528), and indicated that there is not a current API and there is work to be done on rolling out the new version of FCC and other improvements before the API becomes a priority. 
@ameliejyc and I think that an alternative would be to scrape the user's profile page and compare the completed challenges on it with a list of the challenges in each section in the prereq requirements. This will involve significantly more work than just querying the API. We may need to increase the time allowed for this issue up from 4h.

**Comment by astroash** [comment]
Need to add nock test and return object for error handling
