### ISSUE TITLE
Input GitHub page URL to view prerequisite information

### ISSUE THREAD

**Issue by ameliejyc** [ameliejyc/prereq-check#6]
As a selection panel member I can input the URL of an applicant's GitHub page in order to see their prerequisite information.
As an applicant I can input the URL of my GitHub page in order to see my prerequisite information.

Acceptance criteria:

- [x] Input field for GitHub page URL
- [x] Scrape button which when clicked populates freeCodeCamp username, Codewars username and GitHub username fields
- [ ] Submit button which when clicked displays prerequisite information
- [ ] Should look like designed input URL page (image to follow)

![scrape page 3 2](https://user-images.githubusercontent.com/14337958/30059818-9fd5bbca-9238-11e7-8310-9bdd926a58b0.png)

**Comment by astroash** [comment]
I *think* we can use the request module to scrape the html from their gh pages link. Here's an example bit of code I came across in StackOverflow

```
var request = require('request');
request('http://www.google.com', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log(body) // Print the google web page.
  }
})
```
