### ISSUE TITLE
Address Github API frequency limitations

### ISSUE THREAD

**Issue by BartBucknill** [ameliejyc/prereq-check#66]
[Github has a low rate limit](https://developer.github.com/v3/#rate-limiting) on unauthorised API calls. This frequently causes the app to error. We need to prevent this problem resulting from the rate limit.
Acceptance criteria:

- [x] Increase rate limit for our app.

**Comment by dangerdak** [comment]
woops I'm so used to working on the meetups branch i accidentally worked this in there... that's annoying, sorry!
