### ISSUE TITLE
array methods are fun

### ISSUE THREAD

**Issue by Jwhiles** [ameliejyc/prereq-check#71]
You could rewrite these for loops to use [array.prototype.every](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every) 💖 

https://github.com/ameliejyc/prereq-check/blob/c8f5279192270ca5d7f28fd9e075df3fc01ead12/model/freecodecamp-crawl.js#L5-L39

**Comment by astroash** [comment]
OMG how have I never come across this method before ❣️

**Comment by Jwhiles** [comment]
@astroash  .some is another useful one by the way :)

Looking at the code you've written. The 4 functions now seem to be exactly the same, except they are operating on slightly different data. ;) ;) ;) ;) ;0
